### ISSUE TITLE
Is there a way to segment, cluster or request n number of emails?

### ISSUE THREAD

**Issue by datatalking** [mikez/emlx#1]
@mikez  Thank you for writing and updating this package, its been helpful. I'm parsing through a ton of emails with the below code, is there a way to request or batch retrieve 100 or 245 at a time vs all 42,000 at once I'm guessing it does by default?

```
for filepath in glob.iglob(f"/Users/{username}/Library/Mail/**/*.emlx", recursive=True):
     m = emlx.read(filepath)
```

**Comment by mikez** [comment]
I'm glad this package has been helpful for you. :)

It sounds like you want to parse a subset of your emails at a time.

One idea that works on my system is the following:

```
def parse(start, stop):
    for index, filepath in enumerate(glob.iglob(f"/Users/{username}/Library/Mail/**/*.emlx", recursive=True)):
        if start <= index < stop:
            m = emlx.read(filepath)
```

then you can run

```
parse(0, 100)
parse(100, 200)
parse(200, 300)
```

⚠️ This assumes that `glob.iglob` returns the same order in every run. This may or may not be the case for your system. For a more robust solution, you might consider saving the output of `glob.iglob` into a list and then letting that list decide what batch of files to process next.

I hope that helps.

**Comment by datatalking** [comment]
It does give me a place to start thank you.

Do you accept PR requests or has the repo been deprecated for development?

**Comment by mikez** [comment]
@datatalking Yes, pull requests are possible.
